name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    services:
      trino:
        image: trinodb/trino:360
        ports:
          - 8080:8080

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo
      uses: actions-rs/toolchain@v1.0.6
    - name: Build 
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
